src/lib/View/UserSettings/UpdateViewBuilder.php
| Tickets       |  -
| Tests pass?   | ?
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
Fixed the following error
```
Cannot autowire argument $view of "Ibexa\Bundle\User\Controller\UserSettingsController::updateAction()": it references class "Ibexa\User\View\UserSettings\UpdateView" but no such service exists.
```
while opening User Settings in admin-ui.
=> Fixed deprecated class reference in UpdateViewBuilder

src/bundle/DependencyInjection/Compiler/UserSetting/FormMapperPass.php, src/bundle/DependencyInjection/Compiler/UserSetting/ValueDefinitionPass.php, src/bundle/Resources/config/services/user_settings.yaml
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
=> IBX-1694: Rebranded dependency injection container service tags

src/bundle/Resources/config/ezplatform_default_settings.yaml, src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/services/controllers.yaml
| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern
=> IBX-1696: Rebranded Container parameters and Config Resolver namespaces

composer.json, phpunit.xml, src/contracts/Invitation/InvitationService.php, src/contracts/Invitation/Persistence/Gateway.php, src/contracts/Invitation/Persistence/Handler.php, src/contracts/Invitation/Persistence/InvitationUpdateStruct.php, src/lib/Invitation/InvitationService.php, src/lib/Invitation/Persistence/DoctrineGateway.php, src/lib/Invitation/Persistence/Handler.php, tests/integration/Invitation/InvitationServiceTest.php
| Tickets       |  [IBX-2977](https://issues.ibexa.co/browse/IBX-2977) 
| New feature?  | yes
| Doc needed?   | yes
Needs to be rebased after 
https://github.com/ibexa/user/pull/41
is merged
Relevant commits:
https://github.com/ibexa/user/pull/42/commits/a40c8e112df612b02730496baffde8f8d19c3e24
https://github.com/ibexa/user/pull/42/commits/fc3964c67c7b44cd8bba24d8abadf43e0e53600b
=> IBX-2977: Added API for invitation refreshing

src/bundle/Controller/DefaultProfileImageController.php, src/bundle/Resources/views/profile_image/initials.svg.twig
| Tickets       |  https://issues.ibexa.co/browse/IBX-3070
| Bug fix?      | yes/no
=> IBX-3070: User thumbnail should not be rendered with border and other minor bugs

src/bundle/Resources/config/ezplatform_default_settings.yaml, src/bundle/Resources/config/services/validators.yaml, src/bundle/Resources/translations/validators.en.xliff, src/contracts/Invitation/InvitationService.php, src/contracts/Invitation/Persistence/Handler.php, src/contracts/Invitation/Persistence/InvitationUpdateStruct.php, src/lib/Invitation/InvitationService.php, src/lib/Invitation/Persistence/DoctrineGateway.php, src/lib/Invitation/Persistence/Handler.php, src/lib/Validator/Constraints/EmailInvitation.php, src/lib/Validator/Constraints/EmailInvitationValidator.php, tests/integration/Invitation/InvitationServiceTest.php
https://issues.ibexa.co/browse/IBX-3201
https://issues.ibexa.co/browse/IBX-3361
=> IBX-3201: Added invitation email validation

src/bundle/Resources/config/services.yaml, src/contracts/Invitation/InvitationService.php, src/lib/Form/DataTransformer/InvitationTransformer.php, src/lib/Form/Type/Invitation/InvitationType.php, src/lib/Invitation/InvitationService.php, src/lib/Templating/Twig/InvitationExtension.php
| Tickets       |  [IBX-3514](https://issues.ibexa.co/browse/IBX-3514)
=> IBX-3514: Extracted isExpired method

src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/services/twig.yaml, src/bundle/Twig/UserExtension.php, src/bundle/Twig/UserRuntime.php
| Tickets       |  [IBX-4759](https://issues.ibexa.co/browse/IBX-4759) 
| New feature?  | yes
| Doc needed?   | yes
@ibexa/documentation it would be worth mentioning in https://doc.ibexa.co/en/latest/templating/twig_function_reference/twig_function_reference/#__toc
=> IBX-4759: Created Twig function to fetch current User

composer.json
| **JIRA issue**                          | [IBX-1439](https://issues.ibexa.co/browse/IBX-1439)
| **Requires**                            | ibexa/core#171
| **Type**                                   | feature
| **Target Ibexa version** | `v4.4`
| **BC breaks**                          | not for this package
| **CI build**                      | [3765925652](https://github.com/ibexa/user/actions/runs/3765925652), Behat failing due to dep. mismatch
~This PR bumps `league/flysystem-memory` dependency to use Flysystem v2.~ There are no direct usages of `flysystem-memory` library, however `ibexa/core` ~requires~ required this as dev dependency, so we either have to do it here …
=> IBX-1439: Dropped league/flysystem-memory dependency

src/contracts/Invitation/Persistence/Gateway.php
| Tickets       |  [IBX-4929](https://issues.ibexa.co/browse/IBX-4929)
| Tests pass?   | yes/no
* Gateway.php: Moved extended syntax  to @phpstan-param
=> IBX-4929: Fix PhpDoc

src/bundle/DependencyInjection/Configuration/Parser/Security.php
Just running tests before merge because paranoia.
NB: debug config isn't implemented for the user bundle.
```
php bin/console debug:config ibexa_user:
The extension with alias "ibexa_user" does not have its getConfiguration() method setup.
```
We have doc at https://doc.ibexa.co/en/latest/users/user_management/#changing-and-recovering-passwords
=> Remove outdated config example

features/browser/formats.feature, src/bundle/Resources/translations/user_settings.en.xliff, src/lib/UserSetting/Group/EditContentGroup.php, src/lib/UserSetting/Setting/Language.php
| Tickets       |  https://issues.ibexa.co/browse/IBX-6314
| BC breaks?    | yes/no
| Doc needed?   | yes
=> IBX-6314: Apply microcopy guidelines and adjust translation keys and domains

src/lib/Form/ChoiceList/Loader/AvailableLocaleChoiceLoader.php, tests/lib/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoaderTest.php
Since In-context translations are toggled by a dedicated setting there is no need to have Acholi dialect on the list of available translations. This change will also prevent validation errors because Acholi is not a valid Locale
=> Removed Acholi dialect from the list of available translations

src/bundle/Resources/config/routing.yaml
| Tickets       |  [IBX-6547](https://issues.ibexa.co/browse/IBX-6547)
| New feature?  | Page builder Improvments
Made ibexa.user_settings.update exposed
=> IBX-6547: Made ibexa.user_settings.update exposed

src/bundle/Twig/UserExtension.php
| Tickets       |  [IBX-7276](https://issues.ibexa.co/browse/IBX-7276) 
As a new function was added to the `core` package there is a need to deprecate the existing one
=> IBX-7276: Added deprecation notice for `ibexa_user_get_current` twig function

src/bundle/Controller/PasswordChangeController.php
| Tickets       |  [IBX-7130](https://issues.ibexa.co/browse/IBX-7130) 
=> IBX-7130: Redirect back to user setting after updating password

src/bundle/Controller/UserSettingsController.php
| Tickets       |  [IBX-7037](https://issues.ibexa.co/browse/IBX-7037) 
| New feature?  | yes/no
Related PR: https://github.com/ibexa/admin-ui/pull/1047
=> IBX-7037: Added check if user has permission to change password

composer.json, src/bundle/Controller/PasswordResetController.php, src/contracts/Notification/UserAwareNotificationInterface.php, src/contracts/Notification/UserPasswordReset.php, src/contracts/Notification/UserRegister.php, src/lib/Form/Processor/UserRegisterFormProcessor.php, tests/integration/IbexaTestKernel.php
| Question                 | Answer                                              |
|--------------------------|-----------------------------------------------------|
| **JIRA issue**           | [IBX-7369](https://issues.ibexa.co/browse/IBX-7369) [IBX-7371](https://issues.ibexa.co/browse/IBX-7371) |
| **Type**                 | feature                            |
| **Target Ibexa version** | `v4.6`                                              |
| **BC breaks**            | no                                              |
=> IBX-7369, IBX-7371: Added UserRegister and UserPasswordReset notification

src/bundle/Controller/UserSettingsController.php, src/lib/Form/Type/UserSettingUpdateType.php
| Tickets       |  https://issues.ibexa.co/browse/IBX-6724
| New feature?  |no
| Doc needed?   | yes/no
=> IBX-6724: Simplify context menu

src/bundle/Controller/UserSettingsController.php, src/bundle/Resources/translations/ibexa_user_settings.en.xliff, src/lib/UserSetting/Group/EditContentGroup.php
| Tickets       |  [IBX-7119](https://issues.ibexa.co/browse/IBX-7119), [IBX-7171](https://issues.ibexa.co/browse/IBX-7171), [IBX-7123](https://issues.ibexa.co/browse/IBX-7123)
=> IBX-7119, IBX-7171, IBX-7123: Corrected Headers inconsistency in Account settings

src/bundle/Resources/translations/user_settings.en.xliff, src/lib/UserSetting/Setting/FullDateTimeFormat.php, src/lib/UserSetting/Setting/ShortDateTimeFormat.php
| Tickets       |  https://issues.ibexa.co/browse/IBX-7547
| Doc needed?   | yes/no
=> IDX-7547: Change Full and Short date-time setting labels

src/bundle/Resources/translations/ibexa_user_settings.en.xliff, src/lib/UserSetting/Setting/SubitemsLimit.php
| Tickets       |  https://issues.ibexa.co/browse/IBX-7546
=> IBX-7546: Wrong label in User settings - Browsing section for displayed items

.github/workflows/ci.yaml, composer.json, phpstan-baseline-7.4.neon, phpstan-baseline-8.0.neon, phpstan-baseline.neon, phpstan-baseline.neon.php, phpstan.neon, src/lib/UserSetting/ValueDefinitionGroupRegistryEntry.php
=> Added PHPStan

src/lib/Strategy/DefaultThumbnailStrategy.php, src/lib/UserSetting/UserSetting.php
| **JIRA issue**                          | [IBX-7911](https://issues.ibexa.co/browse/IBX-7911)
| **Requires** | ibexa/core#347
| **Required by** | ibexa/admin-ui#1212
| **Type**                                   | bug
| **Target Ibexa version** | `v4.6`
| **BC breaks**                          | no
This PR replaces usages of magic getters with strict ones introduced via ibexa/core#347 and introduces strict getters for `UserSetting` Value Object, needed by ibexa/admin-ui#1212. See the ibexa/core PR for the reasoning behind this change.
The scope of the changes is limited to code paths executed when calling `ContentTreeController::loadSubreeAction` controller.
=> IBX-7911: Replaced usage of magic getters for load subtree code paths

phpstan-baseline.neon, src/lib/UserSetting/Setting/Language.php, tests/lib/UserSetting/Setting/LanguageTest.php
| :ticket: Issue | IBX-7862 |
When a user has set preferred languages in his browser the first of them is taken into account. The current solution tries to find an intersection between preferred and available languages.
=> IBX-7862: Fixed user setting value

composer.json, phpstan-baseline.neon, src/bundle/Controller/PasswordResetController.php, src/contracts/Notification/UserInvitation.php, src/contracts/Notification/UserPasswordReset.php, src/contracts/Notification/UserRegister.php, src/lib/Invitation/MailSender.php, tests/integration/IbexaTestKernel.php, tests/lib/Invitation/InvitationServiceTest.php
| :ticket: Issue | IBX-8137 |
- https://github.com/ibexa/recipes-dev/pull/127
=> IBX-8137: Moved from swift mailer to symfony mailer

phpstan-baseline.neon, src/bundle/Command/UpdateUserCommand.php, tests/bundle/Command/UpdateUserCommandTest.php
| :ticket: Issue | IBX-8823 |
New `ibexa/user` command and its usage needs to be documented.
=> IBX-8823: Added CLI command to update user

.github/workflows/ci.yaml, composer.json, phpstan-baseline.neon, rector.php, src/lib/Form/Type/Invitation/InvitationType.php, src/lib/Form/Type/Invitation/UserInvitationType.php, src/lib/Form/Type/UserPasswordChangeType.php, src/lib/Form/Type/UserPasswordForgotType.php, src/lib/Form/Type/UserPasswordForgotWithLoginType.php, src/lib/Form/Type/UserPasswordResetType.php, src/lib/Form/Type/UserRegisterType.php, src/lib/Form/Type/UserSettingUpdateType.php
| :ticket: Issue | IBX-9584  |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [Form] Added missing return type declarations
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+.
Sanities.
N/A
=> IBX-9584: Resolved Symfony 6.x deprecations

src/bundle/Resources/views/permission/limiation/limitation_values.html.twig
| :ticket: Issue | N/A       |
> The spaceless filter is deprecated as of Twig 3.12 and will be removed in Twig 4.0.
See https://twig.symfony.com/doc/3.x/deprecated.html 
Limitations and field types rendering.
N/A
=> [Twig] Removed usage of deprecated spaceless filter

phpstan-baseline.neon, src/bundle/DependencyInjection/Configuration/Parser/UserRegistration.php, src/contracts/Notification/UserPasswordReset.php, src/contracts/Notification/UserRegister.php, src/lib/ConfigResolver/ConfigurableRegistrationGroupLoader.php, src/lib/Form/Data/UserInvitationData.php, src/lib/Form/Data/UserPasswordChangeData.php, tests/integration/SampleTest.php, tests/lib/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoaderTest.php, tests/lib/Invitation/InvitationServiceTest.php, tests/lib/Permission/UserPermissionsLimitationTypeTest.php, tests/lib/UserSetting/UserSettingServiceTest.php, tests/lib/UserSetting/ValueDefinitionRegistryTest.php, tests/lib/Validator/Constraint/PasswordTest.php, tests/lib/Validator/Constraint/PasswordValidatorTest.php, tests/lib/Validator/Constraint/UserPasswordValidatorTest.php
| :ticket: Issue | IBX-8552 |
- https://github.com/ibexa/checkout/pull/213
- https://github.com/ibexa/recipes-dev/pull/165
- https://github.com/ibexa/storefront/pull/200
SonarCloud analysis is false positive and relates to change from `$this->assert` to `self::assert`
This fix nothing out of the box in existing instalations - if wrong group is assigned (and it was by default), nothing we can do to fix it. However, this fix new instalations and adds possible configuration with remote content id so we avoid those problems in the future.
=> IBX-8552: Added option to configure registration user group by user group content remote id

src/bundle/DependencyInjection/Configuration/Parser/UserRegistration.php, src/bundle/Resources/config/ibexa_core_default_settings.yaml, src/lib/ConfigResolver/ConfigurableRegistrationGroupLoader.php
| :ticket: Issue | IBX-8552 |
- https://github.com/ibexa/user/pull/98
The remote ID used corresponds to the user group with ID 11, as defined in cleandata.sql. We could consider changing it to something more human-readable, but I’m not sure how that might affect update paths, if at all."
=> IBX-8552: Dropped deprecated group_id config key

rector.php, src/bundle/DependencyInjection/IbexaUserExtension.php
| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. Resolved the following deprecations:
```
* [symfony/http-kernel] Replaced usage of internal Symfony\Component\HttpKernel\DependencyInjection\Extension class
```
Sanities.
=> IBX-9968: Resolved Symfony 7.x deprecations

src/bundle/Resources/views/permission/limiation/limitation_values.html.twig
| :ticket: Issue | IBX-8223 |
https://github.com/ibexa/activity-log/pull/126
https://github.com/ibexa/admin-ui/pull/1542
https://github.com/ibexa/cart/pull/136
https://github.com/ibexa/corporate-account/pull/289
https://github.com/ibexa/order-management/pull/151
https://github.com/ibexa/payment/pull/172
https://github.com/ibexa/permissions/pull/28
https://github.com/ibexa/personalization/pull/369
https://github.com/ibexa/product-catalog/pull/1313
https://github.com/ibexa/segmentation/pull/129
https://github.com/ibexa/shipping/pull/112
https://github.com/ibexa/taxonomy/pull/334
https://github.com/ibexa/workflow/pull/136
Refactored limitation value blocks to use 'ibexa_' prefix
Check if all type of limitations are rendered correctly
=> IBX-8223: Refactored limitation value blocks to use 'ibexa_' prefix

phpstan-baseline.neon, src/lib/Permission/UserPermissionsLimitationType.php
| :ticket: Issue | IBX-9727 |
See https://github.com/ibexa/core/pull/562
N/A
N/A
=> IBX-9727: Add missing type hints to limitation contracts

src/bundle/Resources/translations/ibexa_repository_exceptions.en.xliff
| :ticket: Issue | n/a |
Extracted missing translations after ibexa/core#590 changes.
`TranslationTest` is missing on 4.6, so I'll add it as a follow-up after the release.
=> [UI][i18n] Extracted missing translations

src/bundle/Controller/UserRegisterController.php
| :ticket: Issue | IBX-9727 |
- https://github.com/ibexa/content-forms/pull/95
Adapted to deprecations introduced via https://github.com/ibexa/content-forms/pull/70.
=> Adapted to deprecated `null` value for content structs in `BaseContentType`
