.github/workflows/ci.yaml

Cross org merge of https://github.com/ezsystems/ezplatform-user/pull/102

Cross org merge

---

src/lib/Templating/Twig/DateTimeExtension.php

https://issues.ibexa.co/browse/IBX-1543

IBX-1543: Replaced all time & date related Twig filters

---

src/bundle/Resources/views/user_settings/update.html.twig

IBX-1334: Rebranded ibexa/user to use new namespaces

---

src/bundle/Resources/views/reset_password/index.html.twig
src/bundle/Resources/views/reset_password/invalid_link.html.twig

| **JIRA issue**                          | [IBX-1689](https://issues.ibexa.co/browse/IBX-1689)
| **Type**                                   | improvement
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes
Changed all eZ/ez- frontend classes/variables to ibexa
Related PRs:
- https://github.com/ibexa/admin-ui/pull/111
- https://github.com/ibexa/calendar/pull/15
- https://github.com/ibexa/commerce-admin-ui/pull/23
- https://github.com/ibexa/commerce-base-design/pull/11
- https://github.com/ibexa/commerce-checkout/pull/10
- https://github.com/ibexa/commerce-fieldtypes/pull/11
- https://github.com/ibexa/commerce-page-builder/pull/11
- …

IBX-1689: Change all ez- classes/IDs and eZ variables in frontend part

---

composer.json
src/bundle/Resources/config/services.yaml
src/bundle/Resources/config/services/controllers.yaml
src/bundle/Resources/config/services/test/feature_contexts.yaml
src/bundle/Resources/config/services/user_settings.yaml
src/bundle/Resources/config/services/validators.yaml

IBX-1853: Rebranded services names

---

src/bundle/Controller/PasswordChangeController.php
src/bundle/Controller/PasswordResetController.php
src/bundle/Controller/UserSettingsController.php
src/bundle/Resources/config/routing.yaml
src/bundle/Resources/views/forgot_password/mail/forgot_user_password.html.twig
src/bundle/Resources/views/reset_password/invalid_link.html.twig
src/bundle/Resources/views/user_settings/list.html.twig
src/bundle/Security/Authentication/DefaultAuthenticationFailureHandler.php
src/lib/Form/Processor/UserRegisterFormProcessor.php

IBX-1998: Rebranded routes in ibexa/user repository

---

src/bundle/Resources/config/services/user_settings.yaml

IBX-1696: Removed class parameters from ibexa/user repository

---

src/lib/Form/Type/UserRegisterType.php

IBX-1853: Used rebranded namespaces in comments

---

.github/pull_request_template.md
bootstrap.php
tests/bundle/DependencyInjection/Configuration/Parser/ChangePasswordTest.php
tests/bundle/DependencyInjection/Configuration/Parser/ForgotPasswordTest.php
tests/bundle/DependencyInjection/Configuration/Parser/ResetPasswordTest.php

IBX-1853: Used rebranded Ibexa name in codebase

---

src/bundle/DependencyInjection/IbexaUserExtension.php
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/user_settings.en.xliff

Updated translations

---

src/bundle/Controller/DefaultProfileImageController.php
src/bundle/Resources/config/ezplatform_default_settings.yaml
src/bundle/Resources/config/routing.yaml
src/bundle/Resources/config/services.yaml
src/bundle/Resources/config/services/controllers.yaml
src/bundle/Resources/config/services/profile_image.yaml
src/bundle/Resources/views/profile_image/initials.svg.twig
src/lib/Strategy/DefaultThumbnailStrategy.php

| Tickets       |  [IBX-1572](https://issues.ibexa.co/browse/IBX-1572) 
| New feature?  | yes

IBX-1572: Changed default profile image in user menu

---

behat_suites.yml
src/bundle/DependencyInjection/IbexaUserExtension.php

JIRA: https://issues.ibexa.co/browse/IBX-2322

[Behat] Rebranding

---

src/bundle/Resources/views/profile_image/initials.svg.twig

| Tickets       |  https://issues.ibexa.co/browse/IBX-2417

IBX-2417: Size of avatar in header

---

src/bundle/Controller/UserInvitationController.php
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/user_invitation.en.xliff
src/lib/Form/Type/Invitation/UserInvitationType.php

The message `ibexa.user.invitation.group` existed with two different descriptions. Translations were regenerated

Fixed translation key and added missing translations

---

src/bundle/DependencyInjection/IbexaUserExtension.php

Changed name of configuration for translation extraction

---

src/bundle/Resources/translations/forms.en.xliff
src/lib/Permission/InvitationPolicyProvider.php

| **JIRA issue**                          | [IBX-4452](https://issues.ibexa.co/browse/IBX-4452)
| **Type**                                   | improvement
| **Target Ibexa DXP version** | `v4.4`
| **BC breaks**                          | no
| **Doc needed**                       | no

IBX-4452: Added missing translation definitions

---

features/browser/formats.feature
features/browser/loginMethods.feature

| Tickets       |  [IBX-5798](https://issues.ibexa.co/browse/IBX-5798) 
| Bug fix?      | tests
| New feature?  | yes/no
| BC breaks?    | yes/no
| Tests pass?   | yes/no
| Doc needed?   | yes/no

[Behat] IBX-5798: Ibexa Headless regression tests

---

src/bundle/Resources/views/profile_image/initials.svg.twig

| Tickets       |  [https://issues.ibexa.co/browse/IBX-6419
| Bug fix?      | yno
| New feature?  | yes

IBX-6419: Added user avatar to user references

---

src/bundle/Resources/translations/ibexa_user_settings.en.xliff
src/lib/UserSetting/Setting/CharacterCounter.php

| Tickets       |  https://issues.ibexa.co/browse/IBX-7637

IBX-7637: [User settings] Enabled/Disabled labels should be in upper case

---

src/bundle/Controller/DefaultProfileImageController.php
src/bundle/Resources/views/profile_image/initials.svg.twig

| :ticket: Issue | [IBX-8142](https://issues.ibexa.co/browse/IBX-8142) |
- https://github.com/ibexa/admin-ui/pull/1248
- https://github.com/ibexa/fieldtype-page/pull/123
- https://github.com/ibexa/page-builder/pull/368
- https://github.com/ibexa/scheduler/pull/104
- https://github.com/ibexa/tree-builder/pull/149
- https://github.com/ibexa/corporate-account/pull/243
- https://github.com/ibexa/form-builder/pull/123
- https://github.com/ibexa/personalization/pull/338
- https://github.com/ibexa/product-catalog/pull/1158

IBX-8142: removed deprecated code

---

src/bundle/Command/AuditUserDatabaseCommand.php

IBX-8224: Dropped BackwardCompatibleCommand

---

src/bundle/Command/AuditUserDatabaseCommand.php
src/lib/Form/Data/UserInvitationData.php
src/lib/Form/Data/UserPasswordChangeData.php
src/lib/Form/Data/UserPasswordForgotData.php
src/lib/Form/Data/UserPasswordForgotWithLoginData.php
src/lib/Form/Data/UserPasswordResetData.php
src/lib/Form/Data/UserSettingUpdateData.php
src/lib/Form/Processor/UserRegisterFormProcessor.php
src/lib/Form/Type/UserRegisterType.php

| :ticket: Issue | IBX-8138 |
Applied rules from Symfony 5 Rector set lists.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.

IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists

---

src/lib/EventListener/ViewTemplatesListener.php

| :ticket: Issue | IBX-8534 |
- https://github.com/ibexa/core/pull/435

IBX-8534: Renamed pagelayout parameter

---

composer.json
phpstan-baseline.neon

| :ticket: Issue | N/A |
|----------------|-----|
The following PR bump phpstan/phpstan dependency to ^2.0. 
N/A
N/A

Bump phpstan/phpstan to ^2.0

---

src/lib/Behat/Context/UserSetupContext.php

| :ticket: Issue | IBX-XXXXX |
Fix for errors such as this: https://github.com/ibexa/oss/actions/runs/15334263393/job/43148077870#step:18:1142

[Behat] Fix for doctrine update for 'ezuser' table

---

src/bundle/Twig/UserExtension.php

| :ticket: Issue | IBX-XXXXX |
Fixed deprecation in Twig Function

Fixed deprecation in Twig Function

---

src/bundle/Command/AuditUserDatabaseCommand.php
src/lib/Form/DataMapper/UserRegisterMapper.php
src/lib/Strategy/DefaultThumbnailStrategy.php

| :ticket: Issue | IBX-9947 |
https://github.com/ibexa/core/pull/543

IBX-9947: Rebranded field type identifiers

---

src/bundle/Resources/config/storage/schema.yaml
src/lib/Invitation/Persistence/DoctrineGateway.php

IBX-9941: Use single form in table names

---

src/lib/EventListener/ViewTemplatesListener.php

Fixed PHPStan report
